type Sensor = {
    AIN1: number
    AIN2: number
    serial?: String
    DeviceTypeID: number
    Address: string
    AlarmCode: number
    RecordDateTime: string
    ActualWeight: number
    CargoWeight: number
    AccelPedalPosition: number
    Longitude: number
    Latitude: number
    Altitude: number
    Battery1: number
    Battery2: number
    Battery3: number
    Battery4: number
    BatteryVoltage: number
    CoolantTemp: number
    DIN1: boolean
    DIN2: boolean
    DIN3: boolean
    DOUT1: boolean
    DOUT2: boolean
    DOUT3: boolean
    DevConfig: string
    Direction: number
    DoorStatus: boolean
    EngineStatus: boolean
    EngineTotalRunTime: number
    EventType: number
    FuelLevelPer: number
    GPS: number
    HarshAcceleration: number
    HarshBreaking: number
    HarshTurn: number
    Hum1: number
    Hum2: number
    Hum3: number
    Hum4: number
    IdleTime: number
    IngestionDate: string
    InstantFuelConsum: number
    IsCrash: boolean
    IsFuelCutOff: boolean
    IsLowPower: boolean
    IsOverSpeed: boolean
    IsPowerCutOff: boolean
    IsPowerFromBettary: boolean
    IsSOSHighJack: boolean
    IsValidRecord: boolean
    Mileage: number
    MileageMeter: number
    PacketType: string
    ParsingDate: string
    RPM: number
    SeatBelt: boolean
    SeatBeltStatus: boolean
    SerialNumber: string
    SleepStatus: boolean
    Speed: number
    StatusCode: number
    StoppedTime: number
    StreetSpeed: number
    Temp1: number
    Temp2: number
    Temp3: number
    Temp4: number
    TotalFuelConsum: number
    TotalMileage: number
    VehicleStatus: number
    WeightSensorReading: number
    WeightVolt: number
    WorkingHours: number
}

export { type Sensor}