version: 0.2
phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t socketio-server .
artifacts:
  files:
    - '**/*'
